apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - app.yaml
  - postgres.yaml
  - nginx.yaml
  - secret.yaml

images:
  - name: ghcr.io/david-onwuka/dockerized-multi-container-flask-app
    newName: ghcr.io/david-onwuka/dockerized-multi-container-flask-app
    newTag: 0e2c4480d2d7de50e4bfcaabffed77645b129da3
