apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - app.yaml
  - postgres.yaml
  - nginx.yaml
  - secret.yaml

images:
  - name: ghcr.io/david-onwuka/dockerized-multi-container-flask-app
    newName: ghcr.io/david-onwuka/dockerized-multi-container-flask-app
    newTag: d083250e21905e7f58800a55a548dc5b6d8ccb31
